// Generated by Lasy AI - https://lasy.ai
// Constants for GroomHub - Premium Men's Grooming Platform

import { SubscriptionPlan } from './types';

export const APP_NAME = 'GroomHub';
export const APP_TAGLINE = 'Elevate Your Style, Perfect Your Grooming';
export const APP_DESCRIPTION = 'The ultimate platform for modern men who care about their appearance';

// Subscription Plans
export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    currency: 'EUR',
    interval: null,
    features: [
      'Try 3 beard/hair styles',
      'Basic routine checklist',
      'Limited style tips',
      'Public feed access',
      'Ad-supported experience'
    ]
  },
  {
    id: 'monthly',
    name: 'Monthly Pro',
    price: 9.99,
    currency: 'EUR',
    interval: 'month',
    features: [
      'Unlimited style try-ons',
      'Complete routine checklists',
      'Premium content access',
      'Ad-free experience',
      'Basic gamification & rankings',
      'Priority support'
    ]
  },
  {
    id: 'semestral',
    name: 'Semester Elite',
    price: 39.99,
    currency: 'EUR',
    interval: 'semester',
    popular: true,
    features: [
      'Everything in Monthly Pro',
      'Premium exclusive styles',
      'AI-powered personalized suggestions',
      'Complete history & analytics',
      'Priority customer support',
      'Early access to new features'
    ]
  },
  {
    id: 'annual',
    name: 'Annual VIP',
    price: 59.99,
    currency: 'EUR',
    interval: 'year',
    features: [
      'Everything in Semester Elite',
      'Full lifestyle & trend access',
      'Exclusive VIP content',
      'Feed boost & visibility',
      'VIP support & consultation',
      'Lifetime achievement badges'
    ]
  }
];

// Feature flags by subscription tier
export const FEATURE_ACCESS = {
  free: {
    tryOnLimit: 3,
    premiumStyles: false,
    premiumContent: false,
    aiSuggestions: false,
    adFree: false,
    feedBoost: false,
    analytics: false
  },
  monthly: {
    tryOnLimit: Infinity,
    premiumStyles: false,
    premiumContent: true,
    aiSuggestions: false,
    adFree: true,
    feedBoost: false,
    analytics: false
  },
  semestral: {
    tryOnLimit: Infinity,
    premiumStyles: true,
    premiumContent: true,
    aiSuggestions: true,
    adFree: true,
    feedBoost: false,
    analytics: true
  },
  annual: {
    tryOnLimit: Infinity,
    premiumStyles: true,
    premiumContent: true,
    aiSuggestions: true,
    adFree: true,
    feedBoost: true,
    analytics: true
  }
};

// Gamification
export const POINTS_SYSTEM = {
  dailyCheckin: 10,
  completeRoutine: 25,
  postCreated: 15,
  postLiked: 2,
  commentCreated: 5,
  tryOnShared: 10,
  weeklyStreak: 50,
  monthlyStreak: 200,
  badgeEarned: 100
};

export const LEVEL_THRESHOLDS = [
  0, 100, 250, 500, 1000, 2000, 3500, 5500, 8000, 12000, 17000, 25000
];

// Categories
export const ROUTINE_CATEGORIES = [
  { id: 'skincare', name: 'Skincare', icon: 'Sparkles' },
  { id: 'hair', name: 'Hair Care', icon: 'Scissors' },
  { id: 'beard', name: 'Beard Care', icon: 'User' },
  { id: 'hygiene', name: 'Hygiene', icon: 'Droplets' }
];

export const STYLE_CATEGORIES = [
  { id: 'clothing', name: 'Clothing', icon: 'Shirt' },
  { id: 'shoes', name: 'Shoes', icon: 'FootprintsIcon' },
  { id: 'watches', name: 'Watches', icon: 'Watch' },
  { id: 'accessories', name: 'Accessories', icon: 'Glasses' },
  { id: 'grooming', name: 'Grooming', icon: 'Scissors' }
];

export const FACE_SHAPES = [
  { id: 'oval', name: 'Oval', description: 'Balanced proportions' },
  { id: 'round', name: 'Round', description: 'Equal width and length' },
  { id: 'square', name: 'Square', description: 'Strong jawline' },
  { id: 'heart', name: 'Heart', description: 'Wider forehead' },
  { id: 'diamond', name: 'Diamond', description: 'Narrow forehead and jaw' },
  { id: 'oblong', name: 'Oblong', description: 'Longer than wide' }
];

export const SKIN_TYPES = [
  { id: 'oily', name: 'Oily', description: 'Shiny, prone to acne' },
  { id: 'dry', name: 'Dry', description: 'Flaky, tight feeling' },
  { id: 'combination', name: 'Combination', description: 'Oily T-zone, dry cheeks' },
  { id: 'sensitive', name: 'Sensitive', description: 'Easily irritated' },
  { id: 'normal', name: 'Normal', description: 'Balanced, healthy' }
];

export const HAIR_TYPES = [
  { id: 'straight', name: 'Straight', description: 'No curl pattern' },
  { id: 'wavy', name: 'Wavy', description: 'Loose S-pattern' },
  { id: 'curly', name: 'Curly', description: 'Defined curls' },
  { id: 'coily', name: 'Coily', description: 'Tight curl pattern' }
];

// Navigation
export const MAIN_NAV = [
  { name: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
  { name: 'Try-On', href: '/try-on', icon: 'Camera' },
  { name: 'Routine', href: '/routine', icon: 'CheckSquare' },
  { name: 'Style', href: '/style', icon: 'Shirt' },
  { name: 'Feed', href: '/feed', icon: 'Users' },
  { name: 'Profile', href: '/profile', icon: 'User' }
];

// API Endpoints (for future backend integration)
export const API_ENDPOINTS = {
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    logout: '/api/auth/logout',
    refresh: '/api/auth/refresh'
  },
  tryOn: {
    upload: '/api/try-on/upload',
    process: '/api/try-on/process',
    history: '/api/try-on/history'
  },
  routine: {
    tasks: '/api/routine/tasks',
    complete: '/api/routine/complete',
    progress: '/api/routine/progress'
  },
  social: {
    feed: '/api/social/feed',
    post: '/api/social/post',
    like: '/api/social/like',
    comment: '/api/social/comment'
  },
  subscription: {
    plans: '/api/subscription/plans',
    checkout: '/api/subscription/checkout',
    manage: '/api/subscription/manage'
  }
};

// Image placeholders (for development)
export const PLACEHOLDER_IMAGES = {
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
  beardStyle: 'https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=400&h=600&fit=crop',
  hairStyle: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=600&fit=crop',
  outfit: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=800&h=600&fit=crop',
  watch: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400&h=400&fit=crop',
  shoes: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop'
};

// Regex patterns
export const PATTERNS = {
  email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  password: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d@$!%*?&]{8,}$/,
  url: /^https?:\/\/.+/
};

// Error messages
export const ERROR_MESSAGES = {
  auth: {
    invalidCredentials: 'Invalid email or password',
    emailExists: 'Email already registered',
    weakPassword: 'Password must be at least 8 characters with uppercase, lowercase and number',
    sessionExpired: 'Your session has expired. Please login again.'
  },
  subscription: {
    paymentFailed: 'Payment failed. Please try again.',
    invalidPlan: 'Invalid subscription plan selected.'
  },
  upload: {
    fileTooLarge: 'File size must be less than 5MB',
    invalidFormat: 'Only JPG, PNG and WEBP formats are supported'
  }
};

// Success messages
export const SUCCESS_MESSAGES = {
  auth: {
    registered: 'Account created successfully! Welcome to GroomHub.',
    loggedIn: 'Welcome back!',
    loggedOut: 'Logged out successfully.'
  },
  routine: {
    completed: 'Task completed! Keep up the great work.',
    streakMilestone: 'Congratulations on your streak milestone!'
  },
  social: {
    posted: 'Post shared successfully!',
    liked: 'Post liked!',
    commented: 'Comment added!'
  }
};
