// Generated by Lasy AI - https://lasy.ai
// Types for GroomHub - Premium Men's Grooming Platform

export type SubscriptionTier = 'free' | 'monthly' | 'semestral' | 'annual';

export interface User {
  id: string;
  email: string;
  full_name?: string;
  avatar_url?: string;
  subscription_tier: SubscriptionTier;
  subscription_expires_at?: string;
  created_at: string;
  updated_at: string;
  // Profile details
  age?: number;
  skin_type?: 'oily' | 'dry' | 'combination' | 'sensitive' | 'normal';
  hair_type?: 'straight' | 'wavy' | 'curly' | 'coily';
  face_shape?: 'oval' | 'round' | 'square' | 'heart' | 'diamond' | 'oblong';
  // Gamification
  points: number;
  level: number;
  streak_days: number;
  last_checkin?: string;
}

export interface BeardStyle {
  id: string;
  name: string;
  description: string;
  image_url: string;
  category: 'beard' | 'mustache' | 'goatee' | 'stubble' | 'clean';
  premium: boolean;
  popularity: number;
  recommended_face_shapes: string[];
  created_at: string;
}

export interface HairStyle {
  id: string;
  name: string;
  description: string;
  image_url: string;
  category: 'short' | 'medium' | 'long' | 'fade' | 'undercut' | 'classic';
  premium: boolean;
  popularity: number;
  recommended_face_shapes: string[];
  created_at: string;
}

export interface TryOnHistory {
  id: string;
  user_id: string;
  original_image_url: string;
  result_image_url: string;
  style_type: 'beard' | 'hair';
  style_id: string;
  created_at: string;
  is_favorite: boolean;
  shared: boolean;
}

export interface RoutineTask {
  id: string;
  title: string;
  description: string;
  category: 'skincare' | 'hair' | 'beard' | 'hygiene';
  frequency: 'daily' | 'weekly' | 'monthly';
  time_of_day?: 'morning' | 'afternoon' | 'evening' | 'night';
  premium: boolean;
  order: number;
}

export interface UserRoutine {
  id: string;
  user_id: string;
  task_id: string;
  completed: boolean;
  completed_at?: string;
  streak: number;
  created_at: string;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: 'skincare' | 'hair' | 'beard' | 'fragrance' | 'tools';
  description: string;
  image_url: string;
  affiliate_link?: string;
  price?: number;
  rating: number;
  premium: boolean;
}

export interface StyleGuide {
  id: string;
  title: string;
  description: string;
  category: 'clothing' | 'shoes' | 'watches' | 'accessories' | 'grooming';
  content: string;
  image_url: string;
  premium: boolean;
  author: string;
  created_at: string;
  likes: number;
}

export interface OutfitRecommendation {
  id: string;
  title: string;
  description: string;
  occasion: string;
  season: 'spring' | 'summer' | 'fall' | 'winter' | 'all';
  items: {
    type: string;
    name: string;
    image_url: string;
    link?: string;
  }[];
  premium: boolean;
  created_at: string;
}

export interface Post {
  id: string;
  user_id: string;
  user?: User;
  content: string;
  image_url?: string;
  type: 'style' | 'routine' | 'transformation' | 'tip';
  likes_count: number;
  comments_count: number;
  created_at: string;
  updated_at: string;
}

export interface Comment {
  id: string;
  post_id: string;
  user_id: string;
  user?: User;
  content: string;
  created_at: string;
}

export interface Like {
  id: string;
  post_id: string;
  user_id: string;
  created_at: string;
}

export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'grooming' | 'style' | 'social' | 'streak' | 'achievement';
  requirement: string;
  points: number;
  rarity: 'common' | 'rare' | 'epic' | 'legendary';
}

export interface UserBadge {
  id: string;
  user_id: string;
  badge_id: string;
  badge?: Badge;
  earned_at: string;
}

export interface Ranking {
  user_id: string;
  user?: User;
  category: 'overall' | 'grooming' | 'style' | 'social';
  rank: number;
  score: number;
  period: 'daily' | 'weekly' | 'monthly' | 'all_time';
}

export interface Notification {
  id: string;
  user_id: string;
  title: string;
  message: string;
  type: 'routine' | 'social' | 'achievement' | 'subscription' | 'system';
  read: boolean;
  action_url?: string;
  created_at: string;
}

export interface SubscriptionPlan {
  id: SubscriptionTier;
  name: string;
  price: number;
  currency: string;
  interval: 'month' | 'semester' | 'year' | null;
  features: string[];
  popular?: boolean;
  stripe_price_id?: string;
}

export interface Payment {
  id: string;
  user_id: string;
  amount: number;
  currency: string;
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  subscription_tier: SubscriptionTier;
  stripe_payment_id?: string;
  created_at: string;
}

export interface AdminStats {
  total_users: number;
  active_users: number;
  premium_users: number;
  total_revenue: number;
  monthly_revenue: number;
  total_posts: number;
  total_try_ons: number;
  engagement_rate: number;
}
