// Generated by Lasy AI - https://lasy.ai
'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { 
  Sparkles, 
  CheckSquare, 
  CreditCard, 
  Lock, 
  ArrowLeft,
  Crown,
  Shield
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card } from '@/components/ui/card';
import { SUBSCRIPTION_PLANS, APP_NAME } from '@/lib/constants';
import { auth } from '@/lib/supabase';
import type { SubscriptionTier } from '@/lib/types';

export default function CheckoutPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const planId = searchParams.get('plan') as SubscriptionTier || 'monthly';
  
  const [loading, setLoading] = useState(false);
  const [user, setUser] = useState<any>(null);
  const [paymentMethod, setPaymentMethod] = useState<'card' | 'paypal'>('card');
  
  const selectedPlan = SUBSCRIPTION_PLANS.find(p => p.id === planId) || SUBSCRIPTION_PLANS[1];

  useEffect(() => {
    checkAuth();
  }, []);

  const checkAuth = async () => {
    const { data } = await auth.getUser();
    if (!data.user) {
      router.push(`/auth?redirect=/checkout?plan=${planId}`);
    } else {
      setUser(data.user);
    }
  };

  const handleCheckout = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      // Simulate payment processing
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // In production, integrate with Stripe:
      // const response = await fetch('/api/create-checkout-session', {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({ planId, userId: user.id })
      // });
      // const { url } = await response.json();
      // window.location.href = url;

      router.push('/dashboard?payment=success');
    } catch (error) {
      console.error('Payment failed:', error);
      alert('Payment failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  if (!user) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 flex items-center justify-center">
        <div className="text-white">Loading...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center space-x-2 mb-6">
            <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-xl flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <span className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
              {APP_NAME}
            </span>
          </Link>
          
          <Link href="/#pricing" className="inline-flex items-center text-slate-400 hover:text-white transition-colors">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to pricing
          </Link>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Order Summary */}
          <div>
            <h2 className="text-2xl font-bold text-white mb-6">Order Summary</h2>
            
            <Card className="bg-slate-800/50 border-slate-700 p-6 mb-6">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="text-xl font-bold text-white mb-1">{selectedPlan.name} Plan</h3>
                  {selectedPlan.popular && (
                    <span className="inline-block bg-gradient-to-r from-blue-500 to-cyan-500 text-white text-xs font-bold px-2 py-1 rounded">
                      MOST POPULAR
                    </span>
                  )}
                </div>
                <div className="text-right">
                  <div className="text-3xl font-bold text-white">€{selectedPlan.price}</div>
                  {selectedPlan.interval && (
                    <div className="text-sm text-slate-400">per {selectedPlan.interval}</div>
                  )}
                </div>
              </div>

              <div className="border-t border-slate-700 pt-4 mt-4">
                <h4 className="text-sm font-semibold text-slate-300 mb-3">Included features:</h4>
                <ul className="space-y-2">
                  {selectedPlan.features.map((feature, index) => (
                    <li key={index} className="flex items-start text-sm text-slate-300">
                      <CheckSquare className="w-4 h-4 text-green-500 mr-2 flex-shrink-0 mt-0.5" />
                      <span>{feature}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </Card>

            {/* Security Badges */}
            <div className="grid grid-cols-2 gap-4">
              <Card className="bg-slate-800/30 border-slate-700 p-4">
                <Shield className="w-8 h-8 text-blue-400 mb-2" />
                <div className="text-sm font-semibold text-white">Secure Payment</div>
                <div className="text-xs text-slate-400">256-bit SSL encryption</div>
              </Card>
              <Card className="bg-slate-800/30 border-slate-700 p-4">
                <Crown className="w-8 h-8 text-yellow-400 mb-2" />
                <div className="text-sm font-semibold text-white">Money Back</div>
                <div className="text-xs text-slate-400">30-day guarantee</div>
              </Card>
            </div>
          </div>

          {/* Payment Form */}
          <div>
            <h2 className="text-2xl font-bold text-white mb-6">Payment Details</h2>
            
            <Card className="bg-slate-800/50 border-slate-700 p-6">
              <form onSubmit={handleCheckout} className="space-y-6">
                {/* Payment Method Selection */}
                <div>
                  <Label className="text-slate-300 mb-3 block">Payment Method</Label>
                  <div className="grid grid-cols-2 gap-3">
                    <button
                      type="button"
                      onClick={() => setPaymentMethod('card')}
                      className={`p-4 rounded-lg border-2 transition-all ${
                        paymentMethod === 'card'
                          ? 'border-blue-500 bg-blue-500/10'
                          : 'border-slate-700 bg-slate-900/50'
                      }`}
                    >
                      <CreditCard className="w-6 h-6 text-white mx-auto mb-2" />
                      <div className="text-sm text-white font-medium">Credit Card</div>
                    </button>
                    <button
                      type="button"
                      onClick={() => setPaymentMethod('paypal')}
                      className={`p-4 rounded-lg border-2 transition-all ${
                        paymentMethod === 'paypal'
                          ? 'border-blue-500 bg-blue-500/10'
                          : 'border-slate-700 bg-slate-900/50'
                      }`}
                    >
                      <div className="text-xl font-bold text-white mb-2">PayPal</div>
                      <div className="text-xs text-slate-400">Fast & Secure</div>
                    </button>
                  </div>
                </div>

                {paymentMethod === 'card' && (
                  <>
                    {/* Card Number */}
                    <div>
                      <Label htmlFor="cardNumber" className="text-slate-300">Card Number</Label>
                      <div className="relative mt-1">
                        <CreditCard className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                        <Input
                          id="cardNumber"
                          type="text"
                          placeholder="1234 5678 9012 3456"
                          className="pl-10 bg-slate-900/50 border-slate-600 text-white placeholder:text-slate-500"
                          required
                        />
                      </div>
                    </div>

                    {/* Expiry & CVC */}
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <Label htmlFor="expiry" className="text-slate-300">Expiry Date</Label>
                        <Input
                          id="expiry"
                          type="text"
                          placeholder="MM/YY"
                          className="mt-1 bg-slate-900/50 border-slate-600 text-white placeholder:text-slate-500"
                          required
                        />
                      </div>
                      <div>
                        <Label htmlFor="cvc" className="text-slate-300">CVC</Label>
                        <Input
                          id="cvc"
                          type="text"
                          placeholder="123"
                          className="mt-1 bg-slate-900/50 border-slate-600 text-white placeholder:text-slate-500"
                          required
                        />
                      </div>
                    </div>

                    {/* Cardholder Name */}
                    <div>
                      <Label htmlFor="cardName" className="text-slate-300">Cardholder Name</Label>
                      <Input
                        id="cardName"
                        type="text"
                        placeholder="John Doe"
                        className="mt-1 bg-slate-900/50 border-slate-600 text-white placeholder:text-slate-500"
                        required
                      />
                    </div>
                  </>
                )}

                {/* Billing Address */}
                <div>
                  <Label htmlFor="country" className="text-slate-300">Country</Label>
                  <select
                    id="country"
                    className="mt-1 w-full bg-slate-900/50 border border-slate-600 text-white rounded-md px-3 py-2"
                    required
                  >
                    <option value="">Select country</option>
                    <option value="PT">Portugal</option>
                    <option value="ES">Spain</option>
                    <option value="FR">France</option>
                    <option value="DE">Germany</option>
                    <option value="UK">United Kingdom</option>
                    <option value="US">United States</option>
                  </select>
                </div>

                {/* Terms */}
                <div className="flex items-start">
                  <input
                    type="checkbox"
                    id="terms"
                    className="mt-1 mr-2"
                    required
                  />
                  <Label htmlFor="terms" className="text-sm text-slate-400">
                    I agree to the{' '}
                    <Link href="#" className="text-blue-400 hover:text-blue-300">Terms of Service</Link>
                    {' '}and{' '}
                    <Link href="#" className="text-blue-400 hover:text-blue-300">Privacy Policy</Link>
                  </Label>
                </div>

                {/* Submit Button */}
                <Button
                  type="submit"
                  className="w-full bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white py-6 text-lg"
                  disabled={loading}
                >
                  <Lock className="w-5 h-5 mr-2" />
                  {loading ? 'Processing...' : `Pay €${selectedPlan.price}`}
                </Button>

                <div className="text-center text-xs text-slate-500">
                  Your payment is secured with 256-bit SSL encryption
                </div>
              </form>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
