// Generated by Lasy AI - https://lasy.ai
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Camera, Upload, Sparkles, ArrowLeft, Wand2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { APP_NAME } from '@/lib/constants';

export default function TryOnPage() {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);

  const beardStyles = [
    { id: 1, name: 'Classic Full Beard', image: '🧔', premium: false },
    { id: 2, name: 'Goatee', image: '🧔‍♂️', premium: false },
    { id: 3, name: 'Stubble', image: '😎', premium: false },
    { id: 4, name: 'Van Dyke', image: '🎩', premium: true },
    { id: 5, name: 'Handlebar Mustache', image: '🥸', premium: true },
    { id: 6, name: 'Soul Patch', image: '😏', premium: true }
  ];

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setSelectedImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
      {/* Header */}
      <nav className="bg-slate-950/80 backdrop-blur-lg border-b border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/dashboard" className="flex items-center space-x-2">
              <ArrowLeft className="w-5 h-5 text-slate-400" />
              <span className="text-slate-300">Back to Dashboard</span>
            </Link>
            <Link href="/" className="flex items-center space-x-2">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-xl flex items-center justify-center">
                <Sparkles className="w-6 h-6 text-white" />
              </div>
              <span className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
                {APP_NAME}
              </span>
            </Link>
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-white mb-2">AI Try-On Studio</h1>
          <p className="text-slate-400 text-lg">
            Upload your photo and try different beard and hair styles instantly
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Upload Section */}
          <Card className="bg-slate-800/50 border-slate-700 p-8">
            <h2 className="text-2xl font-bold text-white mb-6">Your Photo</h2>
            
            {!selectedImage ? (
              <label className="flex flex-col items-center justify-center w-full h-96 border-2 border-dashed border-slate-600 rounded-xl cursor-pointer hover:border-blue-500 transition-colors">
                <Upload className="w-16 h-16 text-slate-500 mb-4" />
                <span className="text-slate-400 text-lg mb-2">Click to upload your photo</span>
                <span className="text-slate-500 text-sm">PNG, JPG up to 10MB</span>
                <input
                  type="file"
                  className="hidden"
                  accept="image/*"
                  onChange={handleImageUpload}
                />
              </label>
            ) : (
              <div className="relative">
                <img
                  src={selectedImage}
                  alt="Your photo"
                  className="w-full h-96 object-cover rounded-xl"
                />
                <Button
                  onClick={() => setSelectedImage(null)}
                  className="absolute top-4 right-4 bg-slate-900/80 hover:bg-slate-800"
                >
                  Change Photo
                </Button>
              </div>
            )}
          </Card>

          {/* Styles Section */}
          <Card className="bg-slate-800/50 border-slate-700 p-8">
            <h2 className="text-2xl font-bold text-white mb-6">Choose a Style</h2>
            
            <div className="grid grid-cols-2 gap-4">
              {beardStyles.map((style) => (
                <button
                  key={style.id}
                  disabled={!selectedImage}
                  className={`p-6 rounded-xl border-2 transition-all ${
                    selectedImage
                      ? 'border-slate-600 hover:border-blue-500 bg-slate-900/50 hover:bg-slate-900'
                      : 'border-slate-700 bg-slate-900/30 opacity-50 cursor-not-allowed'
                  }`}
                >
                  <div className="text-4xl mb-3">{style.image}</div>
                  <div className="text-white font-medium mb-1">{style.name}</div>
                  {style.premium && (
                    <span className="inline-block bg-gradient-to-r from-yellow-500 to-orange-500 text-white text-xs px-2 py-1 rounded">
                      Premium
                    </span>
                  )}
                </button>
              ))}
            </div>

            {selectedImage && (
              <Button className="w-full mt-6 bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white py-6">
                <Wand2 className="w-5 h-5 mr-2" />
                Apply Style with AI
              </Button>
            )}
          </Card>
        </div>

        {/* Info Banner */}
        <Card className="bg-gradient-to-br from-blue-500/20 to-cyan-500/20 border-blue-500/30 p-6 mt-8">
          <div className="flex items-start space-x-4">
            <Camera className="w-8 h-8 text-blue-400 flex-shrink-0" />
            <div>
              <h3 className="text-lg font-bold text-white mb-2">Pro Tips for Best Results</h3>
              <ul className="text-slate-300 text-sm space-y-1">
                <li>• Use a front-facing photo with good lighting</li>
                <li>• Make sure your face is clearly visible</li>
                <li>• Avoid sunglasses or hats that cover your face</li>
                <li>• Premium styles offer more realistic results</li>
              </ul>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}
