// Generated by Lasy AI - https://lasy.ai
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { CheckSquare, Sparkles, ArrowLeft, Plus, Clock, Droplet, Scissors, Sparkle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { APP_NAME } from '@/lib/constants';

export default function RoutinePage() {
  const [completedTasks, setCompletedTasks] = useState<number[]>([]);

  const routines = {
    morning: [
      { id: 1, title: 'Face Wash', description: 'Cleanse with gentle face wash', icon: Droplet, category: 'skincare' },
      { id: 2, title: 'Moisturizer', description: 'Apply facial moisturizer', icon: Sparkle, category: 'skincare' },
      { id: 3, title: 'Beard Oil', description: 'Apply beard oil and comb', icon: Scissors, category: 'beard' },
      { id: 4, title: 'Hair Styling', description: 'Style hair with product', icon: Sparkle, category: 'hair' }
    ],
    evening: [
      { id: 5, title: 'Face Wash', description: 'Deep cleanse before bed', icon: Droplet, category: 'skincare' },
      { id: 6, title: 'Night Cream', description: 'Apply night moisturizer', icon: Sparkle, category: 'skincare' },
      { id: 7, title: 'Beard Balm', description: 'Condition beard overnight', icon: Scissors, category: 'beard' }
    ]
  };

  const toggleTask = (taskId: number) => {
    setCompletedTasks(prev =>
      prev.includes(taskId)
        ? prev.filter(id => id !== taskId)
        : [...prev, taskId]
    );
  };

  const categoryColors: Record<string, string> = {
    skincare: 'from-blue-500 to-cyan-500',
    beard: 'from-orange-500 to-red-500',
    hair: 'from-purple-500 to-pink-500'
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
      {/* Header */}
      <nav className="bg-slate-950/80 backdrop-blur-lg border-b border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/dashboard" className="flex items-center space-x-2">
              <ArrowLeft className="w-5 h-5 text-slate-400" />
              <span className="text-slate-300">Back to Dashboard</span>
            </Link>
            <Link href="/" className="flex items-center space-x-2">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-xl flex items-center justify-center">
                <Sparkles className="w-6 h-6 text-white" />
              </div>
              <span className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
                {APP_NAME}
              </span>
            </Link>
          </div>
        </div>
      </nav>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-white mb-2">Daily Routine</h1>
          <p className="text-slate-400 text-lg">
            Stay consistent with your grooming habits
          </p>
        </div>

        {/* Progress Card */}
        <Card className="bg-gradient-to-br from-blue-500/20 to-cyan-500/20 border-blue-500/30 p-6 mb-8">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-2xl font-bold text-white">Today's Progress</h3>
              <p className="text-slate-300">
                {completedTasks.length} of {routines.morning.length + routines.evening.length} tasks completed
              </p>
            </div>
            <div className="text-5xl font-bold text-white">
              {Math.round((completedTasks.length / (routines.morning.length + routines.evening.length)) * 100)}%
            </div>
          </div>
          <div className="w-full bg-slate-700 rounded-full h-3">
            <div
              className="bg-gradient-to-r from-blue-500 to-cyan-500 h-3 rounded-full transition-all duration-500"
              style={{
                width: `${(completedTasks.length / (routines.morning.length + routines.evening.length)) * 100}%`
              }}
            ></div>
          </div>
        </Card>

        {/* Morning Routine */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-2xl font-bold text-white flex items-center">
              <Clock className="w-6 h-6 mr-2 text-yellow-400" />
              Morning Routine
            </h2>
            <Button variant="outline" size="sm" className="border-slate-600 text-slate-300">
              <Plus className="w-4 h-4 mr-2" />
              Add Task
            </Button>
          </div>

          <div className="space-y-3">
            {routines.morning.map((task) => (
              <Card
                key={task.id}
                className={`bg-slate-800/50 border-slate-700 p-4 transition-all duration-300 ${
                  completedTasks.includes(task.id) ? 'opacity-60' : ''
                }`}
              >
                <div className="flex items-center space-x-4">
                  <button
                    onClick={() => toggleTask(task.id)}
                    className={`w-6 h-6 rounded-md border-2 flex items-center justify-center transition-all ${
                      completedTasks.includes(task.id)
                        ? 'bg-gradient-to-r from-blue-500 to-cyan-500 border-blue-500'
                        : 'border-slate-600'
                    }`}
                  >
                    {completedTasks.includes(task.id) && (
                      <CheckSquare className="w-4 h-4 text-white" />
                    )}
                  </button>

                  <div className={`w-12 h-12 bg-gradient-to-br ${categoryColors[task.category]} rounded-xl flex items-center justify-center`}>
                    <task.icon className="w-6 h-6 text-white" />
                  </div>

                  <div className="flex-1">
                    <h3 className={`text-lg font-semibold ${completedTasks.includes(task.id) ? 'text-slate-500 line-through' : 'text-white'}`}>
                      {task.title}
                    </h3>
                    <p className="text-slate-400 text-sm">{task.description}</p>
                  </div>

                  <span className="text-xs text-slate-500 uppercase">{task.category}</span>
                </div>
              </Card>
            ))}
          </div>
        </div>

        {/* Evening Routine */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-2xl font-bold text-white flex items-center">
              <Clock className="w-6 h-6 mr-2 text-blue-400" />
              Evening Routine
            </h2>
            <Button variant="outline" size="sm" className="border-slate-600 text-slate-300">
              <Plus className="w-4 h-4 mr-2" />
              Add Task
            </Button>
          </div>

          <div className="space-y-3">
            {routines.evening.map((task) => (
              <Card
                key={task.id}
                className={`bg-slate-800/50 border-slate-700 p-4 transition-all duration-300 ${
                  completedTasks.includes(task.id) ? 'opacity-60' : ''
                }`}
              >
                <div className="flex items-center space-x-4">
                  <button
                    onClick={() => toggleTask(task.id)}
                    className={`w-6 h-6 rounded-md border-2 flex items-center justify-center transition-all ${
                      completedTasks.includes(task.id)
                        ? 'bg-gradient-to-r from-blue-500 to-cyan-500 border-blue-500'
                        : 'border-slate-600'
                    }`}
                  >
                    {completedTasks.includes(task.id) && (
                      <CheckSquare className="w-4 h-4 text-white" />
                    )}
                  </button>

                  <div className={`w-12 h-12 bg-gradient-to-br ${categoryColors[task.category]} rounded-xl flex items-center justify-center`}>
                    <task.icon className="w-6 h-6 text-white" />
                  </div>

                  <div className="flex-1">
                    <h3 className={`text-lg font-semibold ${completedTasks.includes(task.id) ? 'text-slate-500 line-through' : 'text-white'}`}>
                      {task.title}
                    </h3>
                    <p className="text-slate-400 text-sm">{task.description}</p>
                  </div>

                  <span className="text-xs text-slate-500 uppercase">{task.category}</span>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
