// Generated by Lasy AI - https://lasy.ai
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import {
  LayoutDashboard,
  Camera,
  CheckSquare,
  Shirt,
  Users,
  Trophy,
  Settings,
  LogOut,
  TrendingUp,
  Award,
  Zap,
  Crown,
  Sparkles,
  Bell,
  User
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { createClient } from '@/lib/supabase-client';
import { APP_NAME } from '@/lib/constants';

export default function DashboardPage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const supabase = createClient();

  useEffect(() => {
    checkUser();
  }, []);

  const checkUser = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        router.push('/auth');
      } else {
        setUser(user);
      }
    } catch (error) {
      console.error('Error checking user:', error);
      router.push('/auth');
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    router.push('/');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 flex items-center justify-center">
        <div className="text-white text-xl">Loading...</div>
      </div>
    );
  }

  const stats = [
    { label: 'Try-Ons', value: '12', icon: Camera, color: 'from-blue-500 to-cyan-500' },
    { label: 'Streak Days', value: '7', icon: Zap, color: 'from-yellow-500 to-orange-500' },
    { label: 'Badges', value: '5', icon: Award, color: 'from-purple-500 to-pink-500' },
    { label: 'Level', value: '3', icon: Trophy, color: 'from-green-500 to-emerald-500' }
  ];

  const quickActions = [
    { label: 'Try New Style', icon: Camera, href: '/try-on', color: 'from-blue-500 to-cyan-500' },
    { label: 'Daily Routine', icon: CheckSquare, href: '/routine', color: 'from-purple-500 to-pink-500' },
    { label: 'Style Guide', icon: Shirt, href: '/style', color: 'from-orange-500 to-red-500' },
    { label: 'Social Feed', icon: Users, href: '/feed', color: 'from-green-500 to-emerald-500' }
  ];

  const recentActivity = [
    { action: 'Tried "Classic Beard" style', time: '2 hours ago', icon: Camera },
    { action: 'Completed morning routine', time: '5 hours ago', icon: CheckSquare },
    { action: 'Earned "Grooming Master" badge', time: '1 day ago', icon: Award },
    { action: 'Posted transformation photo', time: '2 days ago', icon: Users }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
      {/* Top Navigation */}
      <nav className="bg-slate-950/80 backdrop-blur-lg border-b border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/" className="flex items-center space-x-2">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-xl flex items-center justify-center">
                <Sparkles className="w-6 h-6 text-white" />
              </div>
              <span className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
                {APP_NAME}
              </span>
            </Link>

            <div className="flex items-center space-x-4">
              <Button variant="ghost" size="icon" className="text-slate-300 hover:text-white">
                <Bell className="w-5 h-5" />
              </Button>
              <Button variant="ghost" size="icon" className="text-slate-300 hover:text-white">
                <User className="w-5 h-5" />
              </Button>
              <Button
                variant="ghost"
                onClick={handleLogout}
                className="text-slate-300 hover:text-white"
              >
                <LogOut className="w-5 h-5 mr-2" />
                Logout
              </Button>
            </div>
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Welcome Section */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-white mb-2">
            Welcome back, {user?.user_metadata?.full_name || 'Champion'}!
          </h1>
          <p className="text-slate-400 text-lg">
            Ready to level up your grooming game today?
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {stats.map((stat, index) => (
            <Card key={index} className="bg-slate-800/50 border-slate-700 p-6">
              <div className="flex items-center justify-between mb-4">
                <div className={`w-12 h-12 bg-gradient-to-br ${stat.color} rounded-xl flex items-center justify-center`}>
                  <stat.icon className="w-6 h-6 text-white" />
                </div>
                <TrendingUp className="w-5 h-5 text-green-500" />
              </div>
              <div className="text-3xl font-bold text-white mb-1">{stat.value}</div>
              <div className="text-sm text-slate-400">{stat.label}</div>
            </Card>
          ))}
        </div>

        {/* Quick Actions */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">Quick Actions</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {quickActions.map((action, index) => (
              <Link key={index} href={action.href}>
                <Card className="bg-slate-800/50 border-slate-700 p-6 hover:bg-slate-800 transition-all duration-300 hover:scale-105 cursor-pointer">
                  <div className={`w-12 h-12 bg-gradient-to-br ${action.color} rounded-xl flex items-center justify-center mb-4`}>
                    <action.icon className="w-6 h-6 text-white" />
                  </div>
                  <div className="text-lg font-semibold text-white">{action.label}</div>
                </Card>
              </Link>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Recent Activity */}
          <div className="lg:col-span-2">
            <Card className="bg-slate-800/50 border-slate-700 p-6">
              <h2 className="text-2xl font-bold text-white mb-6">Recent Activity</h2>
              <div className="space-y-4">
                {recentActivity.map((activity, index) => (
                  <div key={index} className="flex items-center space-x-4 p-4 bg-slate-900/50 rounded-lg">
                    <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center flex-shrink-0">
                      <activity.icon className="w-5 h-5 text-white" />
                    </div>
                    <div className="flex-1">
                      <div className="text-white font-medium">{activity.action}</div>
                      <div className="text-sm text-slate-400">{activity.time}</div>
                    </div>
                  </div>
                ))}
              </div>
            </Card>
          </div>

          {/* Progress & Upgrade */}
          <div className="space-y-6">
            {/* Progress Card */}
            <Card className="bg-slate-800/50 border-slate-700 p-6">
              <h3 className="text-xl font-bold text-white mb-4">Your Progress</h3>
              <div className="space-y-4">
                <div>
                  <div className="flex justify-between text-sm mb-2">
                    <span className="text-slate-400">Level 3</span>
                    <span className="text-slate-400">75%</span>
                  </div>
                  <div className="w-full bg-slate-700 rounded-full h-2">
                    <div className="bg-gradient-to-r from-blue-500 to-cyan-500 h-2 rounded-full" style={{ width: '75%' }}></div>
                  </div>
                </div>
                <div className="text-sm text-slate-400">
                  250 XP until Level 4
                </div>
              </div>
            </Card>

            {/* Upgrade Card */}
            <Card className="bg-gradient-to-br from-blue-500/20 to-cyan-500/20 border-blue-500/30 p-6">
              <Crown className="w-12 h-12 text-yellow-400 mb-4" />
              <h3 className="text-xl font-bold text-white mb-2">Upgrade to Premium</h3>
              <p className="text-slate-300 text-sm mb-4">
                Unlock unlimited styles, exclusive content, and advanced features
              </p>
              <Link href="/checkout?plan=monthly">
                <Button className="w-full bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white">
                  View Plans
                </Button>
              </Link>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
