// Generated by Lasy AI - https://lasy.ai
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { 
  LayoutDashboard,
  Camera,
  CheckSquare,
  Shirt,
  Users,
  User,
  TrendingUp,
  Award,
  Flame,
  Target,
  Calendar,
  Bell,
  Settings,
  LogOut,
  Crown,
  Sparkles,
  ArrowRight,
  Menu,
  X
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { APP_NAME, MAIN_NAV } from '@/lib/constants';

export default function DashboardPage() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [user, setUser] = useState({
    name: 'John Doe',
    email: 'john@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    subscription: 'free',
    level: 5,
    points: 1250,
    streak: 7
  });

  // Mock data
  const stats = [
    { label: 'Current Streak', value: user.streak, icon: Flame, color: 'from-orange-500 to-red-500' },
    { label: 'Total Points', value: user.points, icon: Award, color: 'from-yellow-500 to-orange-500' },
    { label: 'Level', value: user.level, icon: TrendingUp, color: 'from-blue-500 to-cyan-500' },
    { label: 'Completed Tasks', value: 42, icon: Target, color: 'from-green-500 to-emerald-500' }
  ];

  const todayTasks = [
    { id: 1, title: 'Morning Skincare Routine', category: 'skincare', completed: true },
    { id: 2, title: 'Beard Oil Application', category: 'beard', completed: true },
    { id: 3, title: 'Hair Styling', category: 'hair', completed: false },
    { id: 4, title: 'Evening Moisturizer', category: 'skincare', completed: false }
  ];

  const recentActivity = [
    { id: 1, type: 'try-on', title: 'Tried Classic Beard style', time: '2 hours ago' },
    { id: 2, type: 'badge', title: 'Earned "7-Day Streak" badge', time: '1 day ago' },
    { id: 3, type: 'post', title: 'Shared transformation photo', time: '2 days ago' }
  ];

  const quickActions = [
    { 
      title: 'Try New Style', 
      description: 'Test beard & hair styles with AI',
      icon: Camera, 
      href: '/try-on',
      color: 'from-blue-500 to-cyan-500'
    },
    { 
      title: 'Daily Routine', 
      description: 'Complete your grooming tasks',
      icon: CheckSquare, 
      href: '/routine',
      color: 'from-purple-500 to-pink-500'
    },
    { 
      title: 'Style Guide', 
      description: 'Explore fashion & lifestyle tips',
      icon: Shirt, 
      href: '/style',
      color: 'from-orange-500 to-red-500'
    },
    { 
      title: 'Community', 
      description: 'Connect with other members',
      icon: Users, 
      href: '/feed',
      color: 'from-green-500 to-emerald-500'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
      {/* Top Navigation */}
      <nav className="fixed top-0 w-full bg-slate-950/80 backdrop-blur-lg border-b border-slate-800 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-4">
              <button
                onClick={() => setSidebarOpen(!sidebarOpen)}
                className="lg:hidden text-slate-300 hover:text-white"
              >
                <Menu className="w-6 h-6" />
              </button>
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center">
                  <Sparkles className="w-5 h-5 text-white" />
                </div>
                <span className="text-xl font-bold text-white hidden sm:block">{APP_NAME}</span>
              </div>
            </div>

            <div className="flex items-center space-x-4">
              <Button variant="ghost" size="icon" className="text-slate-300 hover:text-white relative">
                <Bell className="w-5 h-5" />
                <span className="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full" />
              </Button>
              <Link href="/profile">
                <div className="flex items-center space-x-3 cursor-pointer">
                  <div className="hidden sm:block text-right">
                    <p className="text-sm font-medium text-white">{user.name}</p>
                    <p className="text-xs text-slate-400 capitalize">{user.subscription} Plan</p>
                  </div>
                  <img 
                    src={user.avatar} 
                    alt={user.name}
                    className="w-10 h-10 rounded-full border-2 border-blue-500"
                  />
                </div>
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Mobile Sidebar Overlay */}
      {sidebarOpen && (
        <div 
          className="fixed inset-0 bg-black/50 z-40 lg:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      {/* Sidebar */}
      <aside className={`
        fixed top-16 left-0 h-[calc(100vh-4rem)] w-64 bg-slate-900/95 backdrop-blur-lg border-r border-slate-800 z-40
        transform transition-transform duration-300 lg:translate-x-0
        ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}
      `}>
        <div className="p-4 space-y-2">
          {MAIN_NAV.map((item) => {
            const Icon = item.icon === 'LayoutDashboard' ? LayoutDashboard :
                        item.icon === 'Camera' ? Camera :
                        item.icon === 'CheckSquare' ? CheckSquare :
                        item.icon === 'Shirt' ? Shirt :
                        item.icon === 'Users' ? Users : User;
            
            const isActive = item.href === '/dashboard';
            
            return (
              <Link key={item.href} href={item.href}>
                <div className={`
                  flex items-center space-x-3 px-4 py-3 rounded-lg transition-all
                  ${isActive 
                    ? 'bg-gradient-to-r from-blue-500 to-cyan-500 text-white' 
                    : 'text-slate-300 hover:bg-slate-800 hover:text-white'
                  }
                `}>
                  <Icon className="w-5 h-5" />
                  <span className="font-medium">{item.name}</span>
                </div>
              </Link>
            );
          })}
        </div>

        <div className="absolute bottom-4 left-4 right-4 space-y-2">
          <Link href="/settings">
            <div className="flex items-center space-x-3 px-4 py-3 rounded-lg text-slate-300 hover:bg-slate-800 hover:text-white transition-all">
              <Settings className="w-5 h-5" />
              <span className="font-medium">Settings</span>
            </div>
          </Link>
          <div className="flex items-center space-x-3 px-4 py-3 rounded-lg text-slate-300 hover:bg-slate-800 hover:text-red-400 transition-all cursor-pointer">
            <LogOut className="w-5 h-5" />
            <span className="font-medium">Logout</span>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="lg:ml-64 pt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Welcome Section */}
          <div className="mb-8">
            <h1 className="text-3xl sm:text-4xl font-bold text-white mb-2">
              Welcome back, {user.name.split(' ')[0]}! 👋
            </h1>
            <p className="text-slate-400">
              You're on a {user.streak}-day streak! Keep up the great work.
            </p>
          </div>

          {/* Upgrade Banner (for free users) */}
          {user.subscription === 'free' && (
            <Card className="bg-gradient-to-r from-blue-500/20 to-cyan-500/20 border-blue-500/30 p-6 mb-8">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div className="flex items-start space-x-4">
                  <Crown className="w-8 h-8 text-yellow-400 flex-shrink-0" />
                  <div>
                    <h3 className="text-lg font-bold text-white mb-1">Upgrade to Premium</h3>
                    <p className="text-slate-300 text-sm">
                      Unlock unlimited try-ons, premium styles, and AI-powered suggestions
                    </p>
                  </div>
                </div>
                <Link href="/pricing">
                  <Button className="bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white whitespace-nowrap">
                    View Plans
                    <ArrowRight className="ml-2 w-4 h-4" />
                  </Button>
                </Link>
              </div>
            </Card>
          )}

          {/* Stats Grid */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            {stats.map((stat, index) => (
              <Card key={index} className="bg-slate-800/50 border-slate-700 p-6">
                <div className={`w-12 h-12 bg-gradient-to-br ${stat.color} rounded-xl flex items-center justify-center mb-4`}>
                  <stat.icon className="w-6 h-6 text-white" />
                </div>
                <p className="text-2xl font-bold text-white mb-1">{stat.value}</p>
                <p className="text-sm text-slate-400">{stat.label}</p>
              </Card>
            ))}
          </div>

          {/* Quick Actions */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-white mb-4">Quick Actions</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {quickActions.map((action, index) => (
                <Link key={index} href={action.href}>
                  <Card className="bg-slate-800/50 border-slate-700 p-6 hover:bg-slate-800 transition-all duration-300 hover:scale-105 cursor-pointer h-full">
                    <div className={`w-12 h-12 bg-gradient-to-br ${action.color} rounded-xl flex items-center justify-center mb-4`}>
                      <action.icon className="w-6 h-6 text-white" />
                    </div>
                    <h3 className="text-lg font-bold text-white mb-2">{action.title}</h3>
                    <p className="text-sm text-slate-400">{action.description}</p>
                  </Card>
                </Link>
              ))}
            </div>
          </div>

          {/* Two Column Layout */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Today's Tasks */}
            <div className="lg:col-span-2">
              <Card className="bg-slate-800/50 border-slate-700 p-6">
                <div className="flex items-center justify-between mb-6">
                  <h2 className="text-xl font-bold text-white">Today's Routine</h2>
                  <Badge variant="outline" className="border-green-500 text-green-400">
                    {todayTasks.filter(t => t.completed).length}/{todayTasks.length} Complete
                  </Badge>
                </div>
                <div className="space-y-3">
                  {todayTasks.map((task) => (
                    <div 
                      key={task.id}
                      className={`flex items-center space-x-3 p-4 rounded-lg border transition-all ${
                        task.completed 
                          ? 'bg-green-500/10 border-green-500/30' 
                          : 'bg-slate-700/30 border-slate-600 hover:bg-slate-700/50'
                      }`}
                    >
                      <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center ${
                        task.completed ? 'bg-green-500 border-green-500' : 'border-slate-500'
                      }`}>
                        {task.completed && <CheckSquare className="w-4 h-4 text-white" />}
                      </div>
                      <div className="flex-1">
                        <p className={`font-medium ${task.completed ? 'text-slate-400 line-through' : 'text-white'}`}>
                          {task.title}
                        </p>
                        <p className="text-xs text-slate-500 capitalize">{task.category}</p>
                      </div>
                      {!task.completed && (
                        <Button size="sm" variant="ghost" className="text-blue-400 hover:text-blue-300">
                          Complete
                        </Button>
                      )}
                    </div>
                  ))}
                </div>
                <Link href="/routine">
                  <Button variant="outline" className="w-full mt-4 border-slate-600 text-slate-300 hover:bg-slate-700">
                    View Full Routine
                  </Button>
                </Link>
              </Card>
            </div>

            {/* Recent Activity */}
            <div>
              <Card className="bg-slate-800/50 border-slate-700 p-6">
                <h2 className="text-xl font-bold text-white mb-6">Recent Activity</h2>
                <div className="space-y-4">
                  {recentActivity.map((activity) => (
                    <div key={activity.id} className="flex items-start space-x-3">
                      <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center flex-shrink-0">
                        {activity.type === 'try-on' && <Camera className="w-4 h-4 text-white" />}
                        {activity.type === 'badge' && <Award className="w-4 h-4 text-white" />}
                        {activity.type === 'post' && <Users className="w-4 h-4 text-white" />}
                      </div>
                      <div className="flex-1">
                        <p className="text-sm text-white font-medium">{activity.title}</p>
                        <p className="text-xs text-slate-400">{activity.time}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </Card>

              {/* Progress Card */}
              <Card className="bg-slate-800/50 border-slate-700 p-6 mt-4">
                <h3 className="text-lg font-bold text-white mb-4">Level Progress</h3>
                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between text-sm mb-2">
                      <span className="text-slate-400">Level {user.level}</span>
                      <span className="text-slate-400">{user.points}/2000 XP</span>
                    </div>
                    <Progress value={(user.points / 2000) * 100} className="h-2" />
                  </div>
                  <p className="text-xs text-slate-400">
                    {2000 - user.points} XP until Level {user.level + 1}
                  </p>
                </div>
              </Card>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
